
deps-run: &deps-install
  name: Install dependencies
  command: |
    sudo apt update
    sudo apt install -y graphviz
    sudo pip install pipenv
    pipenv install --progress-bar off .[docs,data,spice]

doc-test: &doc-test
  name: Run doctets
  command: make doctest
  working_directory: doc

doc-changeog: &doc-changelog
  name: Merge changelog
  command: python -m towncrier --yes

doc-run: &doc-build
  name: Build documentation
  command: make html SPHINXOPTS='-W -q'
  working_directory: doc

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-changelog
      - run: *doc-test
      - run: *doc-build
      - store_artifacts:
          path: doc/build/html
      - run:
          name: "Built documentation is available at:"
          command: echo "${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/doc/build/html/index.html"

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
